---
- hosts: all
  gather_facts: false
  tasks:

    - name: Install multiple packages
      win_chocolatey:
        name:
         - firefox
         - git
         - notepadplusplus
        state: present
