---
- hosts: all
  gather_facts: false
  tasks:

    - name: Uninstall multiple packages
      win_chocolatey:
        name:
         - git
         - firefox
         - notepadplusplus
        state: absent
