---
- hosts: all
  gather_facts: false
  tasks:

    - name: Uninstall multiple packages
      win_chocolatey:
        name:
         - git
         - firefox
         - notepadplusplus
        pinned: no
        state: absent
      register: pack

    - debug:
        var: pack
